### ISSUE TITLE
Codeguide 

### ISSUE THREAD

**Issue by julevdl** [amosproj/amos-ss2021-project2-context-map#3] opened 2021-04-14 12:10 UTC

**Comment by derwehr** [comment] 2021-04-14 13:05
React already comes with ESLint, so this issue is merely about whether to stick with react-app's own ESLint config or extending it with another one.

I believe the most popular configs are:
- [Airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) - Shareable config for [Airbnb's style guide](https://github.com/airbnb/javascript).
- [Facebook](https://www.npmjs.com/package/eslint-config-fbjs) - Sharable config for Facebook's style guide.
- [Google](https://github.com/google/eslint-config-google) - Shareable config for the [Google style](http://google.github.io/styleguide/javascriptguide.xml).

I'd vote for extending it with the google config. But that's just personal preferance, since im used to it from other projects.

**Comment by AMOSmiriam** [comment] 2021-04-14 13:07
The official W3C Coding Style guides for [JavaScript](https://www.w3schools.com/js/js_conventions.asp).

**Comment by AMOSmiriam** [comment] 2021-04-14 13:10
i think we should keep the most needed rules, like CamelCase for variables here, so you don't have to read through complete "books" every time ;-)

**Comment by derwehr** [comment] 2021-04-14 13:10
> The official W3C Coding Style guides for [JavaScript](https://www.w3schools.com/js/js_conventions.asp).

The W3C guide is by design not a very extensive style guide, but all of the eslint configs above are built upon this

**Comment by AMOSmiriam** [comment] 2021-04-14 13:12
I will have a look in the style guides you posted.

**Comment by AMOSmiriam** [comment] 2021-04-14 13:28
For me, Google would be fine, since this is not extremely extensive, but there are good approaches. For my opinion it could be shorter and more forced on the essential.

**Comment by CatoLeanTruetschel** [comment] 2021-04-19 09:15
Maybe we should also add preferred (mandatory?) settings for typescript, like strict mode settings, not to allow any types implicitly, etc. Do we use typescript or plain javascript?

**Comment by derwehr** [comment] 2021-04-19 10:57
> Maybe we should also add preferred (mandatory?) settings for typescript, like strict mode settings, not to allow any types implicitly, etc.
All of those styleguide above already do enforce strict mode I believe. 

I read some more into it, and it seems the airbnb styleguide is the most common when using react. I'd suggest just using their config for now and, if necessary extend the eslint rules to our likings. 

>  Do we use typescript or plain javascript?
I'm confident in JS but wouldn't mind learning TS, if someone else already is proficient in it.

**Comment by AMOSmiriam** [comment] 2021-04-20 12:33
For me both is ok TS and JS. But from my experience with front-end development with Vue and TS, it is sometimes more difficult to find Typescript examples than with JavaScript. That's why I can imagine it's easier to work with JS, even if I still have to work my way into it.

airbnb is also ok for me.

**Comment by derwehr** [comment] 2021-04-27 23:31
closing, as this has been implemented by pull/21

**Closed by derwehr** 2021-04-27 23:31 UTC
